# Remap pane switching directions to be Vimlike
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Give tmux mouse control instead of terminal
set -g mouse on

set-option -g focus-events on

set -g status-style fg="#e8dcc8",bg="#5c6178"
set -g message-style fg="#e8dcc8",bg="#8b6bd6",fill="#8b6bd6"
set -g mode-style fg="#e8dcc8",bg="#5fb98c",fill="#5fb98c"
set -g pane-active-border-style fg="#a7a8bd"

# Set standard popup utility key bindings
bind-key y display-popup -E -w 90% -h 90% "yazi-nvim"
bind-key g display-popup -E -w 90% -h 90% "lazygit"
bind-key t display-popup -E -w 90% -h 90% "taskwarrior-tui"
bind-key v display-popup -E -w 90% -h 90% "vd"
bind-key s display-popup -E -w 90% -h 90% "sc-im"
